OP_CONNECT_TOKEN: ENC[AES256_GCM,data:AVJhATnxtBs9UnYslTuqzEqUVqgPYgbclxigi3z3kSd+g80JcSYEsyIb0Z1KQXiFPi6JUHIdCDS3Kc+w9uXard44S7IOhjF5c6ZAMgOfcPfkkeEBVN3Opmu0YIAukjVN/TbLZHevbt6wEKDxZxsuG6I0QjE7b9DPwjGQPsAc6VUO8FKicCRogzi3i7JHG3Tg5E/rXdWvu5LefKSf1LkTyTcGlmyhI+g4Way6hcuq+GkW5RPjzSRJpCXpz0z4/bARi5iadMaQ7LZAdCzTglQ6Yl3tUktQU2ilYUam8kmmic6wJkSpbgXnSuO4cwItZXskbdBWUqMPYtSj/kfLLzNrsC6WkBCRFLPgcrQiXj2RoCYfWDIdO/ftfH1GuGrxUUXhbBPV+bZWgTWHOHwhluQzIbJAJmgKNzYL1tHeptH/vudONOGH6nfnq06Zvg4has0tN4Y2EvT9vOJLJjpvIUnsSlOBMW9DL6Eh2tnmb8djJoGYpgsqeBaQgvvAggB0Yo9qMmOFHeJTpWCPvrV8H7pX1XXsNldC6DNZVht91myormxrxX/ofN2F7VG+abv4T/W8fJsmlEEyZ5rijkpltU+q84Pk/zPiXJ2BJICJK30WtDV3pyOXErZ2+oe8XcqGa2IeYuShTeEJ2rp6Flnr4wdd0tSHBJsxA8t1CXa31LH23VWi3qyQM0ZD7tGnbUt4Y8SoRDAV0LdyEp4BGxbNL7Jk935rIlqE9ShAaa0VP420MuEZT597CduWm6M7NBu1wOShRH7jOzMye9h+la6XvJg1p+vB4YUGdiq+hV8AIydpFTgCRUt9ZhUV2yWESDWIZtaS/52MBrMVYB6h3igbeEAUVDrPJA==,iv:/973U5cShySBHOGzxoztilvIF4mOCWcRRRgRLmiwAxo=,tag:IWU2OwBUUNWPg021akd/dg==,type:str]
sops:
  age:
    - recipient: age19mhznjzteas7egvnszjxr0msdd667sezwaz978562q4r30xsjvuqjfve3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRFJHY2hoekZId1lUQ0FU
        S3Q1UWdPVlFtaDlobVh4dW5ZUzhDc3ArdUdFCmZpWDJ5dHF1aHRIWUVQZ0oxZVBs
        ampMbDV5ZldyWld1eTZHMUpFbVhIZnMKLS0tIGtqV3cva1cxOHN4RVlFQ3BuaWV4
        M09EVFMybnZBZ2RMS1pRN0JxQkc0ZjQKmwPYeRousw//N4umvCxBqcS7P6/cUkOH
        BzLGOe4qM6pgmJK6LLKLqa3aNceyotXqLVH7WazMLmV3XK1bCI770A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T17:37:39Z"
  mac: ENC[AES256_GCM,data:lfFktP3lrj+SnUllzq7kjKisUMYcwhaPgF7rqMZ9J+ORSG5Gq/U0yAlUDq5Zapo9wzUk7aWx1RXNy2KsMieBBh2GKclzHouPIvE2iiXKGbgj8mWJNfkElVb/7HkPdTG4Wg5+1UhWGDZh8mwj7+yXVgcQM9i+gB/gTNwrtCSAQqk=,iv:CkqQ2FeNwHgGaoWSQorqz80nyRRjrRPoQio3081Eh14=,tag:8IkfdGubPbRszfFOj8EusQ==,type:str]
  unencrypted_regex: ^(kind)$
  version: 3.12.2
