OP_CONNECT_TOKEN: ENC[AES256_GCM,data:S5NYfjpl42OJ7sA+fc0lqxDj4bebOXZJRi13FXSDLNTq40i2dB7ScvfBPgh71yivUJZp0vn5w3oZRASzMiecl+w2+2CoMD9PH994cxs14Fl1rkSsacjgyIm0MHUHozfhxJz9vQuEu+nmN++6g3MIpgIerFxF4lBY6Fdj2BKFy9qNwvASlsDpq5hUaRxNQMlRxbSj2M4jTs1PKCjBpfqUWw8NRYc7oOHscUf7oZ7y+oKqC2X9nZmShhm87vWQn4VIbTt09+3qK24RgQvFVLUU/HecwKGegeTaE9O6gNKdiO7P3nKjZagdn6RCNKxdsQ+vCvdcy51rmQpdiQZVQKod5np0e9QHB7/HKzxqwzxnCn67ygBYEaH5rhFIfUxS+iI7O9m2otJPSYd2urfVp4SDg5s5yOZlGPMBZ6s6ATkFjG6g8zR0dmjrvfkMkpaJAcymHTZD2k8Da/xhgtnPN55VIZLN1IPtG+blt7K3J2TnmdVUiwQwRm6VBNVAiYqmzwpHSbLUc/5aKVTywusa4u2FCDa7XKoFxnsXS+TY43uz8Ly4mOF3DLRjgMuqqC2KoIBfysYKxQLfOlLSXT1nmdOaO2UTYgYGpmcUKE1rM1gkZ6moO2ixMequUOyPZPt+TWsiH2+AzpQRlIiWm9DlY3/xDV/lBQA06jH93XbmKHe8GiIFRzGbXXXYbySC34KR5T5n7rdY/ZLkpOtBmTuNUv5djxAreMuBFdCmO5e3Sk5EDeV8uFoWTd9sNjX+mYHCLl2nHcD729BXRnQmqCHXIuDAuF3gDz7DU/kyACq7OjluRxlRh6s8dLcfe2lnCmK2T15XhjTlY+KTkcLtHj+Ew8hd1Xm9nQ==,iv:lZ3etv79DAlphDPtrbyPjcxz2aAVRmL9ZiM5viCAyZU=,tag:XXkuqX/vxJ2UKNTEAa9nTw==,type:str]
sops:
    age:
        - recipient: age19mhznjzteas7egvnszjxr0msdd667sezwaz978562q4r30xsjvuqjfve3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUnN4MkQwTDF2UENzM09i
            OWVyNXBjMEM2Mks3aHVKUWNmMHFBSkVpV1hBCit3YnRYVGNBMnYvUUNEdWR1Zmh4
            L0VpZ2orWHkwU3lxTmxGL2hCY3ZtSG8KLS0tIGV2RWRvdHBvZHJTNUpOcmRhR0lF
            czZtWDEzS1RyWVNKYVhDTDhGVXRFQkkKp1hfyfDt03d3MsdGZWlspzRS5D1fQn/z
            ITuZgDZ5tipsXXalN7Q60jEKsRON2KJSMjnNLmaFFP0ThfXRByRL7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T17:36:57Z"
    mac: ENC[AES256_GCM,data:pwpviGUuTWLpScWr0XrZoa4HWOcIxzxw1svGn9BM8JrjsnsIVZh41y7EONMNmuZ02mEknBhilVnZFRH8ii7NeazQCxNmCV+irCJmkyOk8Zu4U6dOQOHwbh2quN8JXrO3uFrXG5Z3tXZPi0dYz+VrxI4bu4sS0M1MiBQywvtkFvs=,iv:i/K4Efn5yWILWDmgTZez62btC+zjDxXQXOtvrj4Q7tg=,tag:Yx6WbfxO5JinQgMy0kfQoQ==,type:str]
    unencrypted_regex: ^(kind)$
    version: 3.12.2
