---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex-auto-languages
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      plex-auto-languages:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/journeydocker/plex-auto-languages
              tag: 1.4.2@sha256:c3af64f63341be249e7c168162b64670addddda80023f9a273dacd347a1aa1b0
            env:
              TZ: America/Toronto
              PLEX_URL: "http://plex.default.svc.cluster.local:32400"
            envFrom:
              - secretRef:
                  name: plex
            resources:
              requests:
                cpu: 75m
                memory: 300M
              limits:
                memory: 600M
