OP_CONNECT_TOKEN: ENC[AES256_GCM,data:IA84ccz4oEeFQxxpm899A28yD/RrP+Ttj24QLaes/TI2kBoToedBUg8Lul3GXKhG0N0jkBVq9zaj50/X+MlrgUgWE9Ol92Hdb7+uJOt7nnJvp5prBryWBigu+ppb22pRD2Bb/sk831dZA3BMkNHGvS74Cv/1H5cDiwjrM2qXlPtkS2cJJclZPAYjcMUdzQJwdkjSszLYvCYaMZ/8mdB8oPIapqJ3210PzmElYC0TL+Ar9GQA7mnUFSmKwuG6Otzrl9aKtg5uAlDg4fH9bUoWI29JuRZoMKqSZzh+9y2CaCNN6AxkjHId+MwUtM+myr2vewRffnMbmORnIPF6nSAfaS2kWYxmbmNhuHdcctRZkO2efRWF2g7rfoU9TWTb+JqQHTs5HiLeyg1fUCgXgS7IIZ86KHzbn5/wYp07/Mg7Xglze2IYYD6uOcou8Ur/tvGWhNv73yYRFND2TGOLzqRsaD2J6DFO0BX2b1uGZ707UO+SQVA9K6dOA+FSJwwgDsUpoel3cEC/XILhw88FfH1vn+Gy2SiuaLXWV0mkqiIMMOq5uwQbHbJGxilf174KG8r7+YDrJLKECIYicSJ5q2jOzaRbKjzBIX3yPGkL49h8mtliDU1kI71f+Ml9qgoaBaftOHZ2pAol0rlZE4olTWemLsjhCEw9yz4kaVrjuZkPWxoyUy7hUEOr7zmDLYflT/WIVAjrUF+avQbL4S4CX1bNmtZcPHRWss3NiGBx1f/povkeIpHDIjtm3tLDHfz6giWL7UoOt4z0zmcQICMT3ZlDnqcxDzZjmpdZgHKyUiemHK+Vglrc6TMD4+JgV404O4brFoA9z0wmMuJJD2jET3GG9j/pjA==,iv:/kwx+38l3NNK7f6/fHpVztXaXjBVHLh0nrcsVQVl2p8=,tag:2d4GtWbDPI+m2NOee988BA==,type:str]
sops:
  age:
    - recipient: age19mhznjzteas7egvnszjxr0msdd667sezwaz978562q4r30xsjvuqjfve3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSlZVQ0dzWll4VExqaWM4
        RXUwQVNLbzF5NVBqU3NKOG83U0QwNVp4d3o0CldOUDFLWGRpNEMrZWpjbUtUcThU
        SFdhclpjWm5JU3owb3pHN0pJQmRFcXMKLS0tIHUrT2xERXlibGhZZFlnVlRwbHRv
        cHk3R3V5b1VBb2toNUpFVjZ2SUVmSFkKjJk99/eRHIQVrj4+1GmO7h8p7zFQtKmm
        pq76+oOvmOhXJJZ2P1faOAPFfT5mUdTZ+wzyMGeF9mYFgq7tMg3f2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T15:47:55Z"
  mac: ENC[AES256_GCM,data:YjBEq4/lquVIgWlcvn5pqoMgx0HraHl92Kov4KDogz2jmnyvaP5eful7IFijWt5Z2F4SPYL5HZ3ad8Bf7lTGphLvMgp8VH3hhg8zw2+PKMvFC1urgpijg0Y7isf1Cd4jVk5ahLurFtWs1+WYMzQKcbTXAPbAmprSpeYTN5vMy/g=,iv:EqAMce1qUvpTJEebRvKPTtdlt7uUu6NoRobqRLr111w=,tag:cthk4mwhK7vcoy0tYIFIcg==,type:str]
  unencrypted_regex: ^(kind)$
  version: 3.12.2
