---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: calibre-bootstrap
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: calibre-bootstrap
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: volsync-calibre
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 8Gi
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 1000
      fsGroup: 1000
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
    capacity: 5Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: calibre
  namespace: default
spec:
  sourcePVC: calibre-0
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: volsync-calibre
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 10Gi
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      daily: 10
      within: 3d
